version: "3.8"

services:
  api:
    image: mercari-build-training/app:latest
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000
    networks:
      - mercari-network

  frontend:
    image: mercari-build-training/web:latest
    build:
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - api
    networks:
      - mercari-network

networks:
  mercari-network:
    driver: bridge